### ISSUE TITLE
TO BE OPTIMISED

### ISSUE THREAD

**Issue by deca12x** [hroyo/SolencodeT9#1]
**### Optimize storage slots**

  - Optimize storage slots
  - Transform modifier functions into internal functions.
  - Change require statement to custom errors and revert statements to also use custom errors.
  - Stop inheriting ownable and create an internal function to that checks if msg.sender == owner without the additional functionality.
  - Optimize the size of variables (for example timestamps do not need to be uint256).
  - Variables that are only set once can be set as immutable if they are initialized in the constructor
  - Variables that do not change in value can be set as constant
  - Stop inheriting the constants contract, move the constants to the Gas.sol contract
  - reset MEMORY variables to 0 in history and payment
  - change array to mapping?

**Comment by deca12x** [comment]
Removed all requires with @BigBangInfinity

**Comment by deca12x** [comment]
Removed ownable - wasn't needed at all - with @BigBangInfinity

**Comment by deca12x** [comment]
I found the info about deleting data, from Lesson 2:

Deleting data from a contract
1. Simple types. You can use
delete myVariable; or myVariable = 0;
2. Arrays
You can use delete myArray; , this will either set the length to zero for a dynamic
array, or set each item to zero for a static array.
3. Structs
You can delete an instance with delete myStructInstance; , unless the struct
contains a mapping
4. Mappings within structs
You need to delete the individual key value pairs.
     delete (myMapping[key]);

**Comment by deca12x** [comment]
Removed constants contract and partly gone through list of storage variables to optimise (public, constant, immutable) - with @BigBangInfinity

**Comment by BigBangInfinity** [comment]
changed variable types (uint256 to uint32, uint8 etc.)
added unchecked saved a lot of gas
removed wasLastOdd, isOddWhitelistUser: useless code

**Comment by BigBangInfinity** [comment]
changed variable types (uint256 to uint32, uint8 etc.)
added unchecked saved a lot of gas
removed wasLastOdd, isOddWhitelistUser: useless code

**Comment by BigBangInfinity** [comment]
enum PaymentType: Refund,  Dividend,  GroupPayment not used

**Comment by rafboard** [comment]
Removed tradePercent variable and slightly refactored code were was being used and it could be simplified.

**Comment by rafboard** [comment]
defaultPayment is not being used can be removed.

**Comment by BigBangInfinity** [comment]
simplified code:
removed unnecessary code and variables, simplified logic of addToWhitelist, made functions and variables private (only functions directly called in the unittest are public), removed events and errors which are not tested in the unittest (with vm.expectEmit and vm.ExpertRevert functions)

**Comment by deca12x** [comment]
deploymnet down to 520329
